import {
    CallHandler,
    ExecutionContext,
    Injectable,
    Logger,
    NestInterceptor,
} from '@nestjs/common';
import { Observable, tap } from 'rxjs';
import { v4 as uuidv4 } from 'uuid';

@Injectable()
export class LoggingInterceptor implements NestInterceptor {
  private readonly logger = new Logger('HTTP');

  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    const hostType = context.getType();
    
    if (hostType === 'http') {
      const request = context.switchToHttp().getRequest();
      const response = context.switchToHttp().getResponse();
      const { method, url, user } = request;
      const startTime = Date.now();
      
      // Request ID might already be generated by some middleware or the exception filter 
      // depends on the order. We ensure one is available.
      const requestId = request.headers['x-request-id'] || uuidv4();
      request.headers['x-request-id'] = requestId;

      return next.handle().pipe(
        tap(() => {
          const latency = Date.now() - startTime;
          const statusCode = response.statusCode;
          const userId = user?.id || 'anonymous';

          this.logger.log({
            requestId,
            method,
            path: url,
            userId,
            statusCode,
            latency: `${latency}ms`,
            timestamp: new Date().toISOString(),
          });
        }),
      );
    }

    return next.handle();
  }
}
